// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXGAaClLkYu-7Ojp1XpLRGHPtnsV3_Bk',
    appId: '1:140933934319:web:3379e25e1bc202d266ff1a',
    messagingSenderId: '140933934319',
    projectId: 'in-lab-assignment',
    authDomain: 'in-lab-assignment.firebaseapp.com',
    storageBucket: 'in-lab-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0Ch3FrEDodGEzcjqzYyfOlQNS-jZbPs',
    appId: '1:140933934319:android:c492e4a3b979e1b566ff1a',
    messagingSenderId: '140933934319',
    projectId: 'in-lab-assignment',
    storageBucket: 'in-lab-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSUv1PAi5xsfuEkspFjCGu9mqd587PiuY',
    appId: '1:140933934319:ios:669b0a745c94c15d66ff1a',
    messagingSenderId: '140933934319',
    projectId: 'in-lab-assignment',
    storageBucket: 'in-lab-assignment.appspot.com',
    iosClientId: '140933934319-tjvrfbi53ldggsuslg0jvf6q5peeo9qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.labAssignment',
  );
}
